### ISSUE TITLE
Error thrown when retrieving all tickets

### ISSUE THREAD

**Issue by tcash21** [tcash21/zendeskR#3]
If custom fields have been added to tickets, an error will be thrown when trying to retrieve all tickets. This happens at this line in `getAllTickets.R`:

`pre.result <- lapply(json.data, function(x) do.call("rbind", x$tickets))`

It's trying to rbind data.frames with an uneven number of columns. I've tried to remedy by using `rbind.fill` with no success yet.

**Comment by gbgmian** [comment]
Same problem here, did you find a solution?

**Comment by tcash21** [comment]
Not yet, but hoping to spend some time on it this weekend.

**Comment by gbgmian** [comment]
I fixed it by using this method:
https://rmazing.wordpress.com/2012/06/19/dont-fill-me-up/

Another problem is that the current api-call is not using the incremental api:
https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-ticket-export

Zendesk archives tickets automatically after 120 days and with the current implementation those archived tickets are not fetched. Would be a great improvement if the endpoint referenced above was used instead, which also is a more "official" way of fetching large amounts of tickets.

Thanks a lot for looking into this!

**Comment by gbgmian** [comment]
@tcash21 Hello! Did you manage to take a look at this issue?

**Comment by tcash21** [comment]
Hey @gbgmian, we're finally back to updating this package now that I finally got a sponsored Zendesk account. @808sAndBR is helping out as well so keep your eyes peeled for updates soon.

**Comment by jim0wheel** [comment]
Hi @tcash21 - I'm getting this error too, along with the following:

`number of columns of result is not a multiple of vector length (arg 1)`

Is it simply a case of waiting for the update?

Thanks for the update!

**Comment by 808sAndBR** [comment]
Hi @jim0wheel are any of the functions working for you? If not, please ensure that you have been granted access to the API from the zendesk admin panel (also that you have admin level access for getAllTickets and getAllSatisfactionRatings. 

If some commands are working but you're having problems specifically on getAllTickets (and you have admin access) are you using the version of this package from CRAN or from github? I believe @tcash21 has implemented different versions of the data-frame combiner in each, so please try installing and rerunning with the version you have not yet.

If none of that helps, I'll have a version using an alternate method that hypothetically will be more resilient ready soon. I can ping you with the branch info when its ready and would love if you could try it out and let us know if it works for you. I added testthat recently for normal functionality but haven't figured out how to recreate random states of zendesk that cause issues.

**Comment by jim0wheel** [comment]
Hi @808sAndBR - thanks for the speedy reply!

As far as I can tell, the account API settings have all been configured correctly. The `getAllUsers` and `getAllTicketMetrics` functions are working as expected - it's only the `getAllTickets` pull that throws up an error.

I believe the package is from CRAN, installed through the wizard in RStudio. I'll try using the Github version, and let you know how I get on.

**Comment by jim0wheel** [comment]
Hi @808sAndBR 

I installed the package using `githubinstall` and get a different error message this time:

`> tickets <- getAllTickets()`
`Error in output[rng, lcols[[i]]] <- matrices[[i]] : `
`  incorrect number of subscripts on matrix`

**Comment by 808sAndBR** [comment]
@jim0wheel Thank for checking and all the additional info! Can you also try getAllSatisfactionRatings() and let me know if it works? It is the only other function besides getAllTickets() that requires additional permission beyond what is given to 'staff' users (ignore this if you are the admin).

Either way, I think I have a new way working but I'm waiting for my script to generate enough test emails for the testing account so I can check that pagination is working as expected. If everything goes as expected I might ask you to install my branch and run a modified command to see if it resolves your issue before submitting the PR to get it merged into the main repo here.

**Comment by 808sAndBR** [comment]
Hi @jim0wheel, if you're feeling wild would you mind installing my general_refactor branch with:

```
devtools::install_github('808sAndBR/zendeskR', ref = 'general_refactor')
```

Then authenticating as usual with zendesk(email, pwd, domain)
Then try running:

```
all_tickets <- zendesk_get('tickets')
```

If you get a chance to do this, please let me know if this runs for you successfully and gives the results you were expecting from getAllTickets. It seems to be working for all my tests, so I am hopeful to implement this strategy behind the scenes of the getAll... functions and hopefull avoid some of the issues we have hit. 

Thanks again for your help!

**Comment by jim0wheel** [comment]
Hi @808sAndBR - thanks for replying! I just tried the `getAllSatisfactionRatings` function and got the following error:

`Error in `[.data.frame`(dataframe, , i) : undefined columns selected`

Do you think this is a permissions issue then?

I'll try the new way now, and let you know how I get on.

**Comment by tcash21** [comment]
Awesome,  closing this issue out now. Thanks @808sAndBR !
